# Generated by Django 6.1.1 on 2026-09-05 01:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Posición del poste dentro de la secuencia del tramo.')),
                ('es_ancla', models.BooleanField(default=False, help_text='True si el usuario lo colocó deliberadamente; False si se generó automáticamente como poste de paso.')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='catalogo.estructuracfe')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['tramo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PosteComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=6)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('rotacion', models.FloatField(default=0)),
                ('espejo', models.BooleanField(default=False)),
                ('orden_z', models.PositiveSmallIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('componente_visual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='catalogo.componentevisual')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='proyectos.poste')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocupantes', to='catalogo.slotanclaje')),
            ],
            options={
                'verbose_name': 'Componente de poste',
                'verbose_name_plural': 'Componentes de poste',
                'ordering': ['orden_z'],
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Tramo',
                'verbose_name_plural': 'Tramos',
            },
        ),
        migrations.AddField(
            model_name='poste',
            name='tramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='proyectos.tramo'),
        ),
        migrations.CreateModel(
            name='PosteModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='catalogo.modulo')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='proyectos.poste')),
            ],
            options={
                'verbose_name': 'Módulo de poste',
                'verbose_name_plural': 'Módulos de poste',
                'unique_together': {('poste', 'modulo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='poste',
            unique_together={('tramo', 'orden')},
        ),
        migrations.CreateModel(
            name='Vano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(help_text='Distancia en metros, calculada vía pyproj (UTM 13N).')),
                ('flecha', models.FloatField(blank=True, help_text='Flecha del conductor, pendiente de cálculo.', null=True)),
                ('poste_fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanos_como_fin', to='proyectos.poste')),
                ('poste_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanos_como_inicio', to='proyectos.poste')),
            ],
            options={
                'verbose_name': 'Vano',
                'verbose_name_plural': 'Vanos',
                'unique_together': {('poste_inicio', 'poste_fin')},
            },
        ),
    ]
