# Generated by Django 6.1.1 on 2026-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramo',
            name='vano_maximo',
            field=models.FloatField(default=109.0, help_text='Distancia máxima en metros entre postes consecutivos. Estándar CFE: 109 m, ajustable por proyecto.'),
        ),
    ]
