# Generated by Django 6.1.1 on 2026-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_tramo_vano_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='altura_m',
            field=models.FloatField(default=12.0, help_text='Altura del poste en metros (dato de norma, no escala el dibujo).'),
        ),
        migrations.AddField(
            model_name='poste',
            name='resistencia_kg',
            field=models.PositiveIntegerField(default=750, help_text='Resistencia del poste en kg.'),
        ),
        migrations.AddField(
            model_name='poste',
            name='tipo_terreno',
            field=models.CharField(choices=[('blando', 'Blando'), ('normal', 'Normal'), ('duro', 'Duro')], default='normal', help_text='Determina la profundidad de empotramiento (sección 03 00 02).', max_length=10),
        ),
        migrations.AddField(
            model_name='postecomponente',
            name='indice',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición dentro de la cantidad de la regla (ej. 0..2 para 3 aisladores).'),
        ),
    ]
