# Generated by Django 6.1.1 on 2026-09-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_poste_altura_m_poste_resistencia_kg_and_more'),
        ('reglas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postecomponente',
            name='regla_origen',
            field=models.ForeignKey(blank=True, help_text='Regla que originó este componente en modo auto. Vacío si lo agregó el usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='reglas.reglaposicionmaterial'),
        ),
    ]
