# Generated by Django 6.1.1 on 2026-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_postecomponente_regla_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó el proyecto o sus postes.'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_diseno', 'En diseño'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('archivado', 'Archivado')], default='en_diseno', max_length=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tension_kv',
            field=models.FloatField(choices=[(13.8, '13.8 kV'), (34.5, '34.5 kV')], default=13.8, help_text='Tensión nominal de la línea.'),
        ),
    ]
