# Generated by Django 6.1.1 on 2026-10-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_conductor'),
        ('proyectos', '0005_proyecto_estado_tension_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramo',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Conductor del tramo; sin él no se calculan flechas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramos', to='catalogo.conductor'),
        ),
        migrations.AddField(
            model_name='tramo',
            name='porcentaje_eds',
            field=models.FloatField(default=20.0, help_text='Tensión de cada día (EDS) como % de la carga de ruptura, a la temperatura de referencia.'),
        ),
        migrations.AddField(
            model_name='tramo',
            name='temperatura_maxima_c',
            field=models.FloatField(default=50.0, help_text='Temperatura del conductor con la que se calcula la flecha máxima.'),
        ),
    ]
