# Generated by Django 6.1.1 on 2026-09-05 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text="Debe coincidir con el id del <symbol> en el sprite SVG (ej. 'cruceta', 'aislador_pin').", unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ancho_px', models.PositiveSmallIntegerField(help_text='Ancho del símbolo en el sistema de coordenadas local del poste.')),
                ('alto_px', models.PositiveSmallIntegerField(help_text='Alto del símbolo en el sistema de coordenadas local del poste.')),
                ('z_index', models.PositiveSmallIntegerField(default=0, help_text='Orden de dibujo: valores mayores se dibujan encima.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente visual',
                'verbose_name_plural': 'Componentes visuales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraCFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estructura CFE',
                'verbose_name_plural': 'Estructuras CFE',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(choices=[('PZA', 'Pieza'), ('M', 'Metro'), ('KG', 'Kilogramo'), ('LOTE', 'Lote')], default='PZA', max_length=10)),
                ('cantidad_estimada', models.BooleanField(default=False, help_text='Marca si la cantidad requerida aún necesita validarse contra catálogo real de proveedor.')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SlotAnclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('x_local', models.FloatField(help_text='Coordenada X en el sistema local del poste (ej. viewBox 300x1200).')),
                ('y_local', models.FloatField(help_text='Coordenada Y en el sistema local del poste.')),
                ('componentes_compatibles', models.ManyToManyField(blank=True, help_text='Tipos de componente que pueden ocupar este slot.', related_name='slots_compatibles', to='catalogo.componentevisual')),
            ],
            options={
                'verbose_name': 'Slot de anclaje',
                'verbose_name_plural': 'Slots de anclaje',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraCFEMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='catalogo.estructuracfe')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='catalogo.material')),
            ],
            options={
                'verbose_name': 'Material por estructura',
                'verbose_name_plural': 'Materiales por estructura',
                'unique_together': {('estructura', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ModuloMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='catalogo.material')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='catalogo.modulo')),
            ],
            options={
                'verbose_name': 'Material por módulo',
                'verbose_name_plural': 'Materiales por módulo',
                'unique_together': {('modulo', 'material')},
            },
        ),
    ]
