# Generated by Django 6.1.1 on 2026-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuracfe',
            name='es_paso_estandar',
            field=models.BooleanField(default=False, help_text='Marca esta estructura como la que usan los postes de paso generados automáticamente (según CFE: 12m, cruceta PT/PR, 3 aisladores de porcelana). Debe haber exactamente una.'),
        ),
    ]
