# Generated by Django 6.1.1 on 2026-09-18 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_estructuracfe_es_paso_estandar'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuracfe',
            name='icono_mapa',
            field=models.FileField(blank=True, help_text='Icono simplificado para marcador de mapa (UtilityPoleMarkers)', null=True, upload_to='estructuras/iconos/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AddField(
            model_name='estructuracfe',
            name='svg_preview',
            field=models.FileField(blank=True, help_text='SVG de vista completa de la estructura (PoleStructures)', null=True, upload_to='estructuras/previews/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
