# Generated by Django 6.1.1 on 2026-09-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_estructuracfe_icono_mapa_estructuracfe_svg_preview'),
        ('reglas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuracfe',
            name='estructura_mt',
            field=models.OneToOneField(blank=True, help_text='Regla normativa de esta estructura (materiales y posiciones). Vacía si aún no está digitalizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estructura_cfe', to='reglas.estructuramt'),
        ),
        migrations.AddField(
            model_name='material',
            name='componente_visual',
            field=models.ForeignKey(blank=True, help_text='Símbolo con el que se dibuja este material sobre el poste. Vacío si no se dibuja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='catalogo.componentevisual'),
        ),
    ]
