# Generated by Django 6.1.1 on 2026-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_estructuracfe_estructura_mt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(help_text="Ej. 'ACSR 336.4 Linnet'.", max_length=100)),
                ('material', models.CharField(choices=[('ACSR', 'ACSR (aluminio con alma de acero)'), ('AAC', 'AAC (aluminio)'), ('AAAC', 'AAAC (aleación de aluminio)'), ('CU', 'Cobre')], default='ACSR', max_length=5)),
                ('calibre', models.CharField(blank=True, help_text="Ej. '336.4 kcmil', '1/0 AWG'.", max_length=20)),
                ('formacion', models.CharField(blank=True, help_text="Hilos aluminio/acero, ej. '26/7'.", max_length=20)),
                ('seccion_mm2', models.FloatField(help_text='Sección transversal total.')),
                ('diametro_mm', models.FloatField()),
                ('peso_kg_m', models.FloatField(help_text='Peso propio por metro.')),
                ('carga_ruptura_kg', models.FloatField(help_text='Carga de ruptura nominal (RBS).')),
                ('modulo_elasticidad_kg_mm2', models.FloatField(help_text='Módulo de elasticidad final del cable completo.')),
                ('coef_dilatacion_c', models.FloatField(help_text='Coeficiente de dilatación térmica lineal, 1/°C.')),
                ('verificado', models.BooleanField(default=False, help_text='True si un técnico confirmó los valores contra la ficha del fabricante o CFE.')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['seccion_mm2', 'codigo'],
            },
        ),
    ]
