# Generated by Django 6.1.1 on 2026-09-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_estructuracfe_icono_mapa_estructuracfe_svg_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('codigo_especificacion', models.CharField(blank=True, help_text='Ej. CFE DCCIAMBT', max_length=50)),
                ('edicion', models.CharField(blank=True, help_text='Ej. Febrero 2014', max_length=50)),
                ('archivo', models.CharField(blank=True, help_text='Ruta o nombre del PDF fuente', max_length=300)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='SeccionNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Ej. '03 00 02'", max_length=20)),
                ('titulo', models.CharField(max_length=250)),
                ('pagina_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='reglas.documentonormativo')),
            ],
            options={
                'ordering': ['documento', 'codigo'],
                'unique_together': {('documento', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PrefijoEstructuraMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Ej. 'T', 'P', 'R'...", max_length=2, unique=True)),
                ('nombre', models.CharField(help_text="Ej. 'Estructuras tipo T'", max_length=100)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefijos_estructura', to='reglas.seccionnormativa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Ej. 'TS3N', 'PD2'...", max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('categoria', models.CharField(blank=True, choices=[('paso_simple', 'Paso simple'), ('paso_doble', 'Paso doble / deflexión moderada'), ('deflexion', 'Deflexión'), ('remate', 'Remate'), ('anclaje', 'Anclaje en línea'), ('subestacion', 'Entrada/salida de subestación')], max_length=20)),
                ('angulo_min', models.FloatField(blank=True, help_text='Grados. Vacío si no aplica.', null=True)),
                ('angulo_max', models.FloatField(blank=True, help_text='Grados. Vacío si no aplica.', null=True)),
                ('es_terminal', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False, help_text='True si un técnico confirmó los datos contra el PDF fuente')),
                ('prefijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='reglas.prefijoestructuramt')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='reglas.seccionnormativa')),
            ],
            options={
                'verbose_name': 'Estructura de media tensión',
                'verbose_name_plural': 'Estructuras de media tensión',
                'ordering': ['prefijo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoEnsamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Ej. 'H004'", max_length=10, unique=True)),
                ('subseccion', models.CharField(choices=[('H0', 'Herrajes'), ('R0', 'Retenidas'), ('C0', 'Conductores y cables'), ('E0', 'Equipo')], max_length=2)),
                ('titulo', models.CharField(max_length=250)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ensambles', to='reglas.seccionnormativa')),
            ],
            options={
                'ordering': ['subseccion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPosicionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.FloatField(default=1)),
                ('condicion', models.CharField(blank=True, help_text="Ej. 'solo si 3F-4H', 'por conductor', 'según ensamble'", max_length=200)),
                ('cantidad_estimada', models.BooleanField(default=False, help_text='True si la cantidad es un supuesto y debe validarse contra catálogo real')),
                ('altura_min_m', models.FloatField(blank=True, null=True)),
                ('altura_max_m', models.FloatField(blank=True, null=True)),
                ('offset_relativo_m', models.FloatField(blank=True, help_text="Desplazamiento en metros respecto a 'posicion_relativa_a', si aplica", null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_posicion', to='catalogo.material')),
                ('posicion_relativa_a', models.ForeignKey(blank=True, help_text='Si este material se posiciona en función de otro (ej. aislador respecto a la cruceta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='reglas.reglaposicionmaterial')),
                ('tipo_estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='reglas.estructuramt')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_posicion_material', to='reglas.seccionnormativa')),
                ('ensamble', models.ForeignKey(blank=True, help_text='Ensamble de la sección 04 que describe este montaje, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_posicion', to='reglas.tipoensamble')),
            ],
            options={
                'ordering': ['tipo_estructura', 'altura_min_m'],
            },
        ),
        migrations.CreateModel(
            name='ReglaEmpotramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_poste_m', models.FloatField()),
                ('resistencia_kg', models.PositiveIntegerField()),
                ('tipo_terreno', models.CharField(choices=[('blando', 'Blando — arena, arcilla suelta y arcilla con arena'), ('normal', 'Normal — tierra común'), ('duro', 'Duro — tepetate, grava y roca')], max_length=10)),
                ('profundidad_cm', models.PositiveIntegerField()),
                ('verificado', models.BooleanField(default=False, help_text='True si un técnico confirmó el valor contra el PDF fuente')),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_empotramiento', to='reglas.seccionnormativa')),
            ],
            options={
                'ordering': ['altura_poste_m', 'tipo_terreno'],
                'unique_together': {('altura_poste_m', 'resistencia_kg', 'tipo_terreno')},
            },
        ),
        migrations.CreateModel(
            name='ComponenteMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('poste', 'Poste'), ('cruceta', 'Cruceta')], max_length=10)),
                ('clave', models.CharField(help_text="Ej. 'PC-11-700', 'PV-200'", max_length=30)),
                ('carga_ruptura_kg', models.FloatField(blank=True, null=True)),
                ('resistencia_fibra_kg_cm2', models.FloatField(blank=True, null=True)),
                ('limite_fluencia_kg_cm2', models.FloatField(blank=True, null=True)),
                ('factor_seguridad', models.FloatField()),
                ('resistencia_trabajo_kg', models.FloatField()),
                ('verificado', models.BooleanField(default=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_mecanicos', to='reglas.seccionnormativa')),
            ],
            options={
                'ordering': ['tipo', 'clave'],
                'unique_together': {('tipo', 'clave')},
            },
        ),
    ]
